#!/usr/bin/env bash
#
# Generates the shim's symbol tables from the CUDA driver stub's export list.
#
# The shim has to export every symbol the real driver exports (ADR-001): when
# the shim *is* libcuda.so.1, a symbol it does not define does not exist as far
# as the application is concerned. The authoritative list is the driver stub
# for the TARGET architecture, read with nm; x86-64 and sbsa genuinely differ
# (640 vs 641 symbols in CUDA 12.6.77), so this runs per configured build.
#
# Usage:
#   gen_symbols.sh <nm> <stub-libcuda.so> <hook-table.inc> <out-dir>
#
# Writes three files into <out-dir>, each only if its content changed, so that
# re-configuring does not force a rebuild:
#
#   tessera_symbol_index.h    TESSERA_SYMBOL_COUNT and one
#                             #define TESSERA_SYM_<name> <index> per symbol.
#                             The index is what a hooked wrapper uses to reach
#                             its counter and its real-function slot in O(1).
#   tessera_symbols.inc       TESSERA_SYMBOL(<index>, "<name>", <hooked>) rows,
#                             sorted by name so a name lookup can binary-search.
#   tessera_trampolines.inc   TESSERA_TRAMP <name>, <index>  (GNU as macro call
#                             syntax) for every symbol that is NOT hooked.
#
# The index space is the union of the stub's exports and the hooked names, so a
# hooked symbol that a given stub does not export still has an index (it is then
# reported below and its slot simply never resolves).
set -euo pipefail

if [ "$#" -ne 4 ]; then
  echo "usage: $0 <nm> <stub-libcuda.so> <hook-table.inc> <out-dir>" >&2
  exit 2
fi

nm_bin=$1
stub=$2
hook_table=$3
out_dir=$4

if ! command -v "$nm_bin" >/dev/null 2>&1; then
  echo "gen_symbols.sh: nm '$nm_bin' is not executable" >&2
  exit 1
fi
if [ ! -r "$stub" ]; then
  echo "gen_symbols.sh: cannot read driver stub '$stub'" >&2
  exit 1
fi
if [ ! -r "$hook_table" ]; then
  echo "gen_symbols.sh: cannot read hook table '$hook_table'" >&2
  exit 1
fi

mkdir -p "$out_dir"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

export LC_ALL=C

# Exported function symbols of the driver stub. Both GNU nm and llvm-nm print
# "<value> <type> <name>"; T is a text symbol, W a weak one, i an indirect one.
"$nm_bin" -D --defined-only "$stub" \
  | awk '$2 ~ /^[TWi]$/ { print $3 }' \
  | grep '^cu' \
  | sort -u > "$work/exported.txt"

exported_count=$(wc -l < "$work/exported.txt")
if [ "$exported_count" -lt 100 ]; then
  echo "gen_symbols.sh: only $exported_count cu* exports read from $stub" >&2
  exit 1
fi

# Hooked symbols: the first argument of every TESSERA_WRAP row, plus the
# hand-written entry points listed in TESSERA_HOOK_MANUAL rows.
grep -oE '^(TESSERA_WRAP|TESSERA_HOOK_MANUAL)\([A-Za-z0-9_]+' "$hook_table" \
  | sed -E 's/^[A-Z_]+\(//' \
  | sort -u > "$work/hooked.txt"

hooked_count=$(wc -l < "$work/hooked.txt")
if [ "$hooked_count" -lt 50 ]; then
  echo "gen_symbols.sh: only $hooked_count hooked symbols read from $hook_table" >&2
  exit 1
fi

missing=$(comm -23 "$work/hooked.txt" "$work/exported.txt" | tr '\n' ' ')

sort -u "$work/exported.txt" "$work/hooked.txt" > "$work/all.txt"
all_count=$(wc -l < "$work/all.txt")

# One pass: index every symbol, marking the hooked ones.
awk -v hooked_file="$work/hooked.txt" \
    -v idx_h="$work/tessera_symbol_index.h" \
    -v sym_inc="$work/tessera_symbols.inc" \
    -v tramp_inc="$work/tessera_trampolines.inc" \
    -v stub="$stub" '
  BEGIN {
    while ((getline name < hooked_file) > 0) { hooked[name] = 1 }
    close(hooked_file)
    banner = "/* Generated by shim/tools/gen_symbols.sh. Do not edit. */\n"
    printf "%s", banner > idx_h
    printf "#ifndef TESSERA_GENERATED_SYMBOL_INDEX_H\n" >> idx_h
    printf "#define TESSERA_GENERATED_SYMBOL_INDEX_H\n\n" >> idx_h
    printf "%s", banner > sym_inc
    printf "/* TESSERA_SYMBOL(index, \"name\", hooked), sorted by name. */\n" >> sym_inc
    printf "%s", banner > tramp_inc
    printf "/* GNU as macro calls; see shim/src/trampoline_*.S. */\n" >> tramp_inc
    n = 0
    nhooked = 0
  }
  {
    name = $1
    printf "#define TESSERA_SYM_%s %d\n", name, n >> idx_h
    printf "TESSERA_SYMBOL(%d, \"%s\", %d)\n", n, name, (name in hooked) ? 1 : 0 >> sym_inc
    if (!(name in hooked)) {
      printf "TESSERA_TRAMP %s, %d\n", name, n >> tramp_inc
    } else {
      nhooked++
    }
    n++
  }
  END {
    printf "\n#define TESSERA_SYMBOL_COUNT %d\n", n >> idx_h
    printf "#define TESSERA_HOOKED_SYMBOL_COUNT %d\n", nhooked >> idx_h
    printf "\n#endif /* TESSERA_GENERATED_SYMBOL_INDEX_H */\n" >> idx_h
  }
' "$work/all.txt"

for f in tessera_symbol_index.h tessera_symbols.inc tessera_trampolines.inc; do
  if [ ! -f "$out_dir/$f" ] || ! cmp -s "$work/$f" "$out_dir/$f"; then
    cp "$work/$f" "$out_dir/$f"
  fi
done

# Machine-readable summary for the CMake caller (it parses these lines).
echo "TESSERA_EXPORTED_COUNT=$exported_count"
echo "TESSERA_HOOKED_COUNT=$hooked_count"
echo "TESSERA_SYMBOL_COUNT=$all_count"
echo "TESSERA_HOOKED_NOT_IN_STUB=$missing"
